---
title: "Port Group Crosswalk"
author: "Josephine Cardelle"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

## Libraries and Functions

```{r}
library(tidyverse)
library(sf)
library(here)
library(dplyr)
library(janitor)
source(here("functions/assign_county.R"))
```

## Data

```{r}
# Processor location information including longitude and latitude
processors <- read.csv(here("data/processed_products/pp_coordinates_zip.csv"))

# County/port info
iopac_ports <- read.csv(here("data/location_info/ports_counties.csv")) %>% 
  clean_names()
```

# Assign Counties and Port Groups

```{r}
processor_county <- assign_county(processors) %>% 
  clean_names() %>% 
  rename(countyfp = county_2, county_1 = county, county = name)

port_county <- iopac_ports %>% 
  select(io_pac_port_group, county) %>% 
  unique()

processor_port <- left_join(processor_county, port_county, by = "county")

sum(is.na(processor_port$io_pac_port_group))

processor_port$io_pac_port_group[is.na(processor_port$io_pac_port_group)] <- "Other"

write.csv(processor_port, file = here("data/processed_products/processor_port.csv"), row.names = FALSE)
```
